### ISSUE TITLE
Base Mapping / Inheritance

### ISSUE THREAD

**Issue by madebybear** [JimBobSquarePants/UmbMapper#1]
First off, thanks for UmbMapper. I think it's a missing piece for me. I'm trying to create a simple example based on in the inheritance examples in UmbMapper.Tests but I think I might be going wrong somewhere (probably just my understanding / code). 

Ideally I'll like somehow achieve the following;
- Add some extra properties to the existing `Home` doctype (thus using it as a base) via inheritance
- Keep all the existing properties and mappings for the `Home` doctype
- Be allowed to override existing `Home` mappings later on in my `InheritedHomeMap`

By way of a simple example, my steps are;

- In the Umbraco back office, add an extra property to `Home` called `Introduction` as a Textarea. 

![image](https://user-images.githubusercontent.com/4785812/30023881-402af5de-9169-11e7-8cb6-a452a918453f.png)

Then, I need to create a new class to represent this with extra property;

    public class InheritedHome : Home
    {
        public InheritedHome(IPublishedContent content) : base(content)
        {
        }

        /// <summary>
        /// Gets or sets the introduction
        /// </summary>
        public virtual string Introduction { get; set; }
    }

So, now I wanted to add the ability to map this extra property, so I modified the `HomeMap` to be `HomeMap<T>` where T : Home. 

    /// <summary>
    /// Configures mapping for the home page
    /// </summary>
    public class HomeMap<T> : UmbMapperConfig<T>
        where T : Home
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HomeMap"/> class.
        /// </summary>
        public HomeMap()
        {                     
            // ... all the existing meta / gallery ones from your sample removed for brevity ...
           
           // original 'Content' tab... 
           this.AddMap(x => x.BodyText).AsLazy();
        }

Created my mapping;

    /// <summary>
    /// Configures mapping for the InheritedHome page
    /// </summary>
    public class InheritedHomeMap : HomeMap<InheritedHome>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InheritedHomeMap"/> class.
        /// </summary>
        public InheritedHomeMap()
        {
            // my new 'Introduction' property
            this.AddMap(x => x.Introduction).AsLazy();
        }
    }

Altered the `HomeController` to use my new `InheritedHome` 

    public override ActionResult Index(RenderModel model)
    {
        InheritedHome inheritedHome = (InheritedHome) model.Content;

        RenderPage<InheritedHome> viewModel = new RenderPage<InheritedHome>(inheritedHome);

        return this.CurrentTemplate(viewModel);
     }

Altered the view `Views\Home.cshtml`

    @inherits UmbracoViewPage<RenderPage<InheritedHome>>

     <h1>@Model.Content.Name</h1>

      // additional intro property
      <p><strong>@Model.Content.Introduction</strong></p>

      @Model.Content.BodyText

Altered the view `Views\Site.cshtml`

     @inherits   UmbracoViewPage<RenderPage<InheritedHome>>

 Finally added the new mapping in the events;

        protected override void ApplicationStarting(UmbracoApplicationBase umbracoApplication, 
        ApplicationContext applicationContext)
        {
            UmbMapperRegistry.AddMapper(new InheritedHomeMap());
           
            var factory = new UmbMapperPublishedContentModelFactory();
            PublishedContentModelFactoryResolver.Current.SetFactory(factory);
        }

Then I run the project and I get following error

`Unable to cast object of type 'Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedContent' to type 'My.Umbraco.App.Models.Pages.InheritedHome'.`

Am I missing a step somewhere?

**Comment by JimBobSquarePants** [comment]
Hi @madebybear

Thanks for such a detailed issue report. I really appreciate it!

The `UmbMapperPublishedContentModelFactory` determines the correct type to map to by reading the document type alias and looking for a map that contains a matching type. In your instance since the type is `InheritedHome` there is no document type alias to match that type.

However... I foresaw this!

The `UmbMapperPublishedContentModelFactory` class contains a virtual method called `ResolveTypeName` which determines what type to return. If you inherit the class and override that property to check for your property and return the correct name then you will be able to map to your type.

https://github.com/JimBobSquarePants/UmbMapper/blob/16c21d8e91485ef1ce726fa1164b996bc4fe97ab/src/UmbMapper.PublishedContentModelFactory/UmbMapperPublishedContentModelFactory.cs#L43

Hope that all makes sense

Cheers

James

**Comment by madebybear** [comment]
Hi James,

Thanks for that. This works for me now. 

My inherited UmbMapperPublishedContentModelFactory...

    public class CustomUmbMapperPublishedContentModelFactory : UmbMapperPublishedContentModelFactory
    {
        public override string ResolveTypeName(IPublishedContent content)
        {
            if (content.DocumentTypeAlias.Equals("home", StringComparison.OrdinalIgnoreCase))
            {
                return nameof(InheritedHome);
            }

            return content.DocumentTypeAlias;
        }
    }

Then in the events, setting the factory to be the one above...

     protected override void ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
      {
            UmbMapperRegistry.AddMapper(new InheritedHomeMap());
           
            var factory = new CustomUmbMapperPublishedContentModelFactory();
            PublishedContentModelFactoryResolver.Current.SetFactory(factory);
      }

Perfect. Everything seems to just work! 👍 

--- 

I also did some playing after the original post and got it working slightly differently. Reading through the documentation again, I realised the word _convention_ was the key - I figured that UmbMapper somewhere was probably looking for `Home` not `InheritedHome`  I reverted my initial changes (from the first post) back to your Umbraco.Sample version but this time;

- I renamed the original `Home`  to `BaseHome` 
- Reworked `HomeMap` to be `BaseHomeMap<BaseHome>` 
- I then used `Home` as my new inherited class so... `Home : BaseHome`
- Inherited the from `BaseHomeMap`  (so  `HomeMap : BaseHomeMap<Home>`) and added my new 
`Introduction` mapping 

So now I need to decide which approach is going to be best moving forward. 

Thank you for your help.

**Comment by JimBobSquarePants** [comment]
No worries, happy to. Really glad you've been giving this a go.

Yeah convention, when possible is definitely the way to go. If you have property value converters for all you document types you can even get away with doing 

```
UmbMapper.AddMapperFor<Home>();
```

I added the granular functionality to allow highly customised configuration but your aim should be to try and reduce configuration as much as possible. 

Cheers

James
