### ISSUE TITLE
UmbMapper for Archetype return null elements

### ISSUE THREAD

**Issue by grifin85** [JimBobSquarePants/UmbMapper#3]
I have model Home

```
    public class HomeViewModel
     {
        public string Title { get; set; }
        public string Description { get; set; }
        public string MetaTitle { get; set; }
        public virtual IEnumerable<CarouselItem> Carousel { get; set; }
     }
```

I have Carouse model

```
      public class CarouselItem
        {
            public string Image { get; set; }
            public string Title { get; set; }    
            public string Text { get; set; }
        }
```

My mapper configs

**HomeMap**

   ```
  public class HomeMap : UmbMapperConfig<HomeViewModel>
     {
         public HomeMap()
         {
             this.AddMap(item => item.Title);
             this.AddMap(item => item.MetaTitle);
             this.AddMap(item => item.Description);
             this.AddMap(item => item.Carousel).SetMapper<ArchetypeFactoryPropertyMapper>();
         }
     }

```
and **CarouselMap** 

```
public class CarouselMap : UmbMapperConfig<CarouselItem>
    {
        public CarouselMap()
        {
            this.AddMap(item => item.Image).SetMapper<UmbracoPickerPropertyMapper>();
            this.AddMap(item => item.Title);
            this.AddMap(item => item.Text);
        }
    }
```

My Action where I make map

  ```
  public override ActionResult Index(RenderModel model)
    {
        var viewModel = model.Content.MapTo(typeof(HomeViewModel));
    
        return CurrentTemplate(viewModel);
    }
```

But for Carousel I get null in list
![architype](https://user-images.githubusercontent.com/16155203/33064979-303a1356-ceb0-11e7-85c4-6e01a8b3212c.PNG)

Could you explain me, what I should to do wrong?

**Comment by JimBobSquarePants** [comment]
Hi @grifin85 

Would it be possible to show screenshots of your doctypes? I should be able to use them to figure out what is missing. 

My first thought is that you are trying to map to string on the `Image` property, the internal `PropertyValueConverter` Umbraco uses doesn't allow that as far as I'm aware. Could you try setting the mapper to ignore the `Image` property and retrying?

Cheers

James

**Comment by grifin85** [comment]
Hi @JimBobSquarePants 
I removed from map image, but do not help me

My Carousel
![architype1](https://user-images.githubusercontent.com/16155203/33085158-8f96b11a-ceec-11e7-9e36-d3f0eadb4ab4.PNG)
![architype2](https://user-images.githubusercontent.com/16155203/33085159-8fb66686-ceec-11e7-9c4b-458497162fb1.PNG)

I think it is because, ArchetypeFieldsetModel we have public IEnumerable<ArchetypePropertyModel> Properties; where we have data. But I don't see in source where using this property when we make mapping

**Comment by JimBobSquarePants** [comment]
@grifin85 What does the home doctype look like?

Did you have a look in the sample in the repository? That's mapping a carousel from Archetype

**Comment by JimBobSquarePants** [comment]
@grifin85 I've added a comprehensive example in the repository that demonstrates exactly how to map a carousel using Archetype. As such I'm closing this as you should be able to replicate the results.
