### ISSUE TITLE
Support mapping to an existing object

### ISSUE THREAD

**Issue by AndyButland** [JimBobSquarePants/UmbMapper#5]
Back having a look over this James and seeing how it fits into our usual workflow using  "UmbracoMapper" that with some colleagues have built and used for a while.  One difference is that when I built that I expected the client to already have created a view model, and then map `IPublishedContent` to that.  In hindsight, 99% of the time that's just adding an extra step, and so better have an instance of the model created as you have it.

However there might be cases where you would want to map to an existing view model or other object.  Perhaps Umbraco content is a small part, and it's already been created from some other source.  Or perhaps you want to map from two different Umbraco sources (have an example in our base build where we create the page specific view model and then map on "base page" items like the common navigation).

Partially completed PR coming with this - it's mostly straightforward of course, but I ran into a problem thinking about how "lazy" mappings would be handled when we already have an object that's not be created as a proxy.

**Comment by JimBobSquarePants** [comment]
Hi @AndyButland 

Definitely a viable use case, I'll move the conversation to the PR. Thanks for getting this started. 👍

**Comment by JimBobSquarePants** [comment]
Finally got this released. Thanks for the idea and initial PR

https://www.nuget.org/packages/UmbMapper/1.1.2
