### ISSUE TITLE
Test Site: Unable to view blog and posts, get a YSOD

### ISSUE THREAD

**Issue by TimGeyssens** [JimBobSquarePants/UmbMapper#7]
Error:
Cannot bind source type Umbraco.Web.Models.RenderModel to model type UmbMapper.Sample.RenderModels.RenderPage`1[[UmbMapper.Sample.Models.Pages.Home, UmbMapper.Sample, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].

**Comment by JimBobSquarePants** [comment]
I think it must be a temporary glitch in your VS instance. I've just ran a clean build in both release and debug with no issue.

![umbmapper](https://user-images.githubusercontent.com/385879/39161939-5c4990f0-47b6-11e8-8dbd-6c9a06cdadc1.JPG)

**Comment by TimGeyssens** [comment]
Yeah homepage runs fine but if I try to go directly to a post it doesnt work

**Comment by TimGeyssens** [comment]
Ok found it I can do @model `IRenderPage<PublishedPage>` on the layout view and use the correct models on the blog and posts

**Comment by JimBobSquarePants** [comment]
Ah my bad, I must have forgotten to update the view. 

I've added all the relevant controllers etc now so it all works. Will try to really flesh out the site with real world examples when I can.

**Comment by TimGeyssens** [comment]
Thanks, using it now for the first time and so far so good :) awesome job!

**Comment by TimGeyssens** [comment]
One thing that would be ace is to add a nav with active state (I used a multi url picker and a custom mapper for that now, to get the ancestor collection) but not sure that is the way to go
